use nitrolaunch::shared::pkg::PackageCategory;

pub static PACKAGE_CATEGORIES: &[PackageCategory] = &[
	PackageCategory::Adventure,
	PackageCategory::Atmosphere,
	PackageCategory::Audio,
	PackageCategory::Blocks,
	PackageCategory::Building,
	PackageCategory::Cartoon,
	PackageCategory::Challenge,
	PackageCategory::Combat,
	PackageCategory::Compatability,
	PackageCategory::Decoration,
	PackageCategory::Economy,
	PackageCategory::Entities,
	PackageCategory::Equipment,
	PackageCategory::Exploration,
	PackageCategory::Extensive,
	PackageCategory::Fantasy,
	PackageCategory::Fonts,
	PackageCategory::Food,
	PackageCategory::GameMechanics,
	PackageCategory::Gui,
	PackageCategory::Items,
	PackageCategory::Language,
	PackageCategory::Library,
	PackageCategory::Lightweight,
	PackageCategory::Magic,
	PackageCategory::Minigame,
	PackageCategory::Mobs,
	PackageCategory::Multiplayer,
	PackageCategory::Optimization,
	PackageCategory::Realistic,
	PackageCategory::Simplistic,
	PackageCategory::Space,
	PackageCategory::Social,
	PackageCategory::Storage,
	PackageCategory::Structures,
	PackageCategory::Technology,
	PackageCategory::Transportation,
	PackageCategory::Tweaks,
	PackageCategory::Utility,
	PackageCategory::VanillaPlus,
	PackageCategory::Worldgen,
];

pub fn package_category_display_name(category: PackageCategory) -> &'static str {
	match category {
		PackageCategory::Adventure => "Adventure",
		PackageCategory::Atmosphere => "Atmosphere",
		PackageCategory::Audio => "Audio",
		PackageCategory::Blocks => "Blocks",
		PackageCategory::Building => "Building",
		PackageCategory::Cartoon => "Cartoon",
		PackageCategory::Challenge => "Challenge",
		PackageCategory::Combat => "Combat",
		PackageCategory::Compatability => "Compatability",
		PackageCategory::Decoration => "Decoration",
		PackageCategory::Economy => "Economy",
		PackageCategory::Entities => "Entities",
		PackageCategory::Equipment => "Equipment",
		PackageCategory::Exploration => "Exploration",
		PackageCategory::Extensive => "Extensive",
		PackageCategory::Fantasy => "Fantasy",
		PackageCategory::Fonts => "Fonts",
		PackageCategory::Food => "Food",
		PackageCategory::GameMechanics => "Game Mechanics",
		PackageCategory::Gui => "Gui",
		PackageCategory::Items => "Items",
		PackageCategory::Language => "Language",
		PackageCategory::Library => "Library",
		PackageCategory::Lightweight => "Lightweight",
		PackageCategory::Magic => "Magic",
		PackageCategory::Minigame => "Minigame",
		PackageCategory::Mobs => "Mobs",
		PackageCategory::Multiplayer => "Multiplayer",
		PackageCategory::Optimization => "Optimization",
		PackageCategory::Realistic => "Realistic",
		PackageCategory::Simplistic => "Simplistic",
		PackageCategory::Space => "Space",
		PackageCategory::Social => "Social",
		PackageCategory::Storage => "Storage",
		PackageCategory::Structures => "Structures",
		PackageCategory::Technology => "Technology",
		PackageCategory::Transportation => "Transportation",
		PackageCategory::Tweaks => "Tweaks",
		PackageCategory::Utility => "Utility",
		PackageCategory::VanillaPlus => "Vanilla+",
		PackageCategory::Worldgen => "Worldgen",
	}
}

pub fn package_category_icon(category: PackageCategory) -> &'static str {
	match category {
		PackageCategory::Adventure => "minecraft",
		PackageCategory::Atmosphere => "sun",
		PackageCategory::Audio => "audio",
		PackageCategory::Blocks => "box",
		PackageCategory::Building => "honeycomb",
		PackageCategory::Cartoon => "palette",
		PackageCategory::Challenge => "dumbbell",
		PackageCategory::Combat => "sword",
		PackageCategory::Compatability => "link",
		PackageCategory::Decoration => "couch",
		PackageCategory::Economy => "graph",
		PackageCategory::Entities => "animal",
		PackageCategory::Equipment => "helmet",
		PackageCategory::Exploration => "search",
		PackageCategory::Extensive => "home",
		PackageCategory::Fantasy => "star",
		PackageCategory::Fonts => "font",
		PackageCategory::Food => "burger",
		PackageCategory::GameMechanics => "dice",
		PackageCategory::Gui => "diagram",
		PackageCategory::Items => "fork",
		PackageCategory::Language => "language",
		PackageCategory::Library => "book",
		PackageCategory::Lightweight => "fullscreen",
		PackageCategory::Magic => "star",
		PackageCategory::Minigame => "controller",
		PackageCategory::Mobs => "animal",
		PackageCategory::Multiplayer => "multiple_users",
		PackageCategory::Optimization => "lightning",
		PackageCategory::Realistic => "picture",
		PackageCategory::Simplistic => "box",
		PackageCategory::Space => "moon",
		PackageCategory::Social => "microphone",
		PackageCategory::Storage => "folder",
		PackageCategory::Structures => "building",
		PackageCategory::Technology => "server",
		PackageCategory::Transportation => "bus",
		PackageCategory::Tweaks => "properties",
		PackageCategory::Utility => "gear",
		PackageCategory::VanillaPlus => "plus",
		PackageCategory::Worldgen => "globe",
	}
}
