package nitro:plugin;

world interface-world {
	export run-plugin: func(hook: string, arg: string, hook-version: u32) -> u32;
	export get-result: func() -> string;

	import get-custom-config: func() -> option<string>;
	import get-data-dir: func() -> string;
	import get-config-dir: func() -> string;
	import get-os-string: func() -> string;
	import get-arch-string: func() -> string;
	import get-pointer-width: func() -> u32;

	import update-hardlink: func(src: string, tgt: string) -> result<_, string>;
	import run-command: func(cmd: string, args: list<string>, working-dir: option<string>, suppress-command-window: bool, silent: bool, wait: bool) -> result<s32, string>;

	import download-bytes: func(url: string) -> result<list<u8>, string>;
	import download-text: func(url: string) -> result<string, string>;
	import download-file: func(url: string, path: string) -> result<_, string>;
}