name: Build and Test
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo Deps
        id: cache-cargo-deps
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libfreetype6-dev \
            libfontconfig1-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libwayland-dev
      - if: ${{ matrix.os == 'ubuntu-latest'}}
        name: Run tests
        run: cargo test --workspace --exclude nitro_gui
      - if: ${{ github.ref_name == 'main' }}
        name: Build CLI Release
        run: cargo build --package nitro_cli --release
      - if: ${{ github.ref_name == 'dev' }}
        name: Build CLI Fast Release
        run: cargo build --package nitro_cli --profile fast_release
      - uses: actions/upload-artifact@v4
        name: Upload CLI artifact
        with:
          name: ${{ matrix.os }}
          path: target/release/nitro*
